In [5]:
import numpy as np

x = np.array([ [45,40,65],
            [4,5,6],
            [10,30,60],
            [20,45,32],
            [56,28,21],
            [3,9,11]])
x

array([[45, 40, 65],
       [ 4,  5,  6],
       [10, 30, 60],
       [20, 45, 32],
       [56, 28, 21],
       [ 3,  9, 11]])

In [6]:
np.apply_over_axes?

In [9]:
x_means = np.apply_over_axes(np.mean, x, axes = 0)
x_means

array([[23.        , 26.16666667, 32.5       ]])

In [12]:
x_demean = x - x_means
x_demean

array([[ 22.        ,  13.83333333,  32.5       ],
       [-19.        , -21.16666667, -26.5       ],
       [-13.        ,   3.83333333,  27.5       ],
       [ -3.        ,  18.83333333,  -0.5       ],
       [ 33.        ,   1.83333333, -11.5       ],
       [-20.        , -17.16666667, -21.5       ]])

In [14]:
x_means.shape

(1, 3)

In [15]:
x.shape

(6, 3)

In [41]:
x_sds = np.apply_over_axes(lambda x, axis: np.std( x, ddof = 0, axis=axis) , x, axes = 0)
x_sds

array([[20.46134567, 14.75823687, 22.76510488]])

In [42]:
x_demean_scaled = x_demean/x_sds
x_demean_scaled

array([[ 1.0751981 ,  0.93732967,  1.42762356],
       [-0.92858018, -1.43422733, -1.16406229],
       [-0.63534433,  0.25974196,  1.20798916],
       [-0.14661792,  1.27612353, -0.02196344],
       [ 1.61279715,  0.12422441, -0.5051591 ],
       [-0.97745282, -1.16319224, -0.94442789]])

In [43]:
from sklearn.preprocessing import StandardScaler
StandardScaler().fit_transform(x)

array([[ 1.0751981 ,  0.93732967,  1.42762356],
       [-0.92858018, -1.43422733, -1.16406229],
       [-0.63534433,  0.25974196,  1.20798916],
       [-0.14661792,  1.27612353, -0.02196344],
       [ 1.61279715,  0.12422441, -0.5051591 ],
       [-0.97745282, -1.16319224, -0.94442789]])

In [40]:
np.std?